// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://legbjstkzfuysxkeofci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZ2Jqc3RremZ1eXN4a2VvZmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTUyNzQsImV4cCI6MjA2NTQ5MTI3NH0.M30j7ivTmyxl1oim2BIeYo8VIZ2Av8rjiQV6SpQQsZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);